const actions = {
    "GET_USER": "GET_USER",
    "SAVE_NEW_USER": "SAVE_NEW_USER",
    "LOGIN_USER": "LOGIN_USER",
    "LOGOUT_USER": "LOGOUT_USER",
    "SET_EMPLOYEE_LIST":"SET_EMPLOYEE_LIST",
    "SET_DESIGNATION_LIST": "SET_DESIGNATION_LIST",
    "SET_BRANCH_LIST": "SET_BRANCH_LIST",
    "RESET_EMPLOYEE_DATA": "RESET_EMPLOYEE_DATA"
}

export default actions
